spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: www1234
    url: jdbc:mysql://172.17.0.3:3306/springbootdemo?characterEncoding=utf-8&useSSL=false
  session:
    store-type: none
server:
  port: 8080
  servlet:
    context-path: /springboot

mybatis:
  mapper-locations: classpath:mapper/*.xml
